name: Linux

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cppstd: ["98", "11", "20"]
        cc: ["gcc-10"]
        cxx: ["g++-10"]
        drafts: ["ON"]
        libzmq: ["4.3.4"]
        libzmqbuild: ["cmake"]
        include:
          - os: "ubuntu-18.04"
            cppstd: 11
            cc: "gcc-7"
            cxx: "g++-7"
            drafts: "OFF"
            libzmq: "4.2.0"
            libzmqbuild: "pkgconfig"
          - os: "ubuntu-latest"
            cppstd: 20
            cc: "gcc-10"
            cxx: "g++-10"
            drafts: "OFF"
            libzmq: "4.3.4"
            libzmqbuild: "cmake"
          - os: "ubuntu-latest"
            cppstd: 17
            cc: "clang-12"
            cxx: "clang++-12"
            drafts: "ON"
            libzmq: "4.3.4"
            libzmqbuild: "cmake"

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./ci_build.sh
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        CMAKE_CPP_STD: -DCMAKE_CXX_STANDARD=${{ matrix.cppstd }}
        ENABLE_DRAFTS: ${{ matrix.drafts }}
        ZMQ_VERSION: ${{ matrix.libzmq }}
        BUILD_TYPE: ${{ matrix.libzmqbuild }}
        VERBOSE: 1
