name: Linux

on: [push, pull_request]

jobs:
  gcc10:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cppstd: ["98", "11", "20"]
        cxx: ["g++-10"]
        drafts: ["ON"]
        libzmq: ["4.3.4"]
        libzmqbuild: ["cmake"]
        include:
          - cppstd: 11
            cxx: "g++-7"
            drafts: "OFF"
            libzmq: "4.2.0"
            libzmqbuild: "pkgconfig"
          - cppstd: 20
            cxx: "g++-10"
            drafts: "OFF"
            libzmq: "4.3.4"
            libzmqbuild: "cmake"

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./ci_build.sh
      env:
        CXX: ${{ matrix.cxx }}
        CMAKE_CPP_STD: -DCMAKE_CXX_STANDARD=${{ matrix.cppstd }}
        ENABLE_DRAFTS: ${{ matrix.drafts }}
        ZMQ_VERSION: ${{ matrix.libzmq }}
        BUILD_TYPE: ${{ matrix.libzmqbuild }}
        VERBOSE: 1
